swagger: '2.0'
info:
  title: API Title
  version: '1.0'
tags:
  - name: LessonLike
    description: '강의에 대해 좋아요 등록 및 해제 및 확인, 좋아요한 강의 및 강의에 좋아요 누른 사람 출력'
paths:
  /like/:
    get:
      tags:
        - LessonLike
      summary: '로그인한 유저가 좋아요 누른 항목 조회'
      parameters:
        - name: Authorization
          in: header
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: '유저가 좋아요 누른 모든 레슨'
          schema:
            type: object
            properties:
              message:
                type: string
                example: '북마크 데이터를 불러오는데 성공하였습니다.'
              data:
                type: array
        '401':
          description: 'Invalid JWT token'
          schema:
            type: string
            example: Unauthorized
  /like/{lesson_id}:
    get:
      tags:
        - LessonLike
      summary: '해당 레슨에 좋아요를 눌렀는지 확인'
      produces:
        - application/json
      parameters:
        - name: Authorization
          in: header
          type: string
        - name: 'lesson_id'
          in: path
          description: 'lesson id'
          type: integer
          format: int32
          required: true
      responses:
        '201':
          description: 레슨 북마크에 성공하였을 때
          schema:
            required:
              - message
              - data
            properties:
              message:
                type: string
                example: '북마크 데이터를 저장하는데 성공하였습니다.'
              data:
                type: boolean
        '401':
          description: 'Invalid JWT token'
          schema:
            type: string
            example: Unauthorized
    put:
      tags:
        - LessonLike
      summary: '해당 레슨 좋아요'
      produces:
        - application/json
      parameters:
        - name: Authorization
          in: header
          type: string
        - name: 'lesson_id'
          in: path
          description: 'lesson id'
          type: integer
          format: int32
          required: true
      responses:
        '200':
          description: 좋아요 등록에 성공할 때
          schema:
            required:
              - message
              - data
            properties:
              message:
                type: string
                example: '좋아요 데이터를 저장하는데 성공하였습니다.'
              data:
                type: boolean
                example: true
        '400':
          description: 레슨 ID가 존재하지 않을 때
          schema:
            type: string
            example: '유효하지 않은 강의 id입니다.'
        '401':
          description: 'Invalid JWT token'
          schema:
            type: string
            example: Unauthorized
    delete:
      tags:
        - LessonLike
      summary: '해당 레슨 좋아요 취소'
      produces:
        - application/json
      parameters:
        - name: Authorization
          in: header
          type: string
        - name: 'lesson_id'
          in: path
          description: 'lesson id'
          type: integer
          format: int32
          required: true
      responses:
        '200':
          description: 북마크 삭제에 성공하였을 때
          schema:
            required:
              - message
              - data
            properties:
              message:
                type: string
                example: '좋아요 데이터를 삭제하는데 성공하였습니다.'
              data:
                type: boolean
                example: true
        '400':
          description: 레슨 ID가 존재하지 않을 때
          schema:
            type: string
            example: '유효하지 않은 강의 id입니다.'
        '401':
          description: 'Invalid JWT token'
          schema:
            type: string
            example: Unauthorized
  /like/{lesson_id}/all:
    get:
      tags:
        - LessonLike
      summary: '해당 레슨에 좋아요를 누른 모든 유저'
      produces:
        - application/json
      parameters:
        - name: Authorization
          in: header
          type: string
        - name: 'lesson_id'
          in: path
          description: 'lesson id'
          type: integer
          format: int32
          required: true
      responses:
        '201':
          description: '불러오는데 성공할 때'
          schema:
            required:
              - message
              - data
            properties:
              message:
                type: string
                example: '강의에 좋아요 누른 사람들을 불러오는데 성공하였습니다.'
              data:
                type: boolean
        '401':
          description: 'Invalid JWT token'
          schema:
            type: array
